"""empty message

Revision ID: 77cbe143aa4f
Revises: e2f03f31d93e
Create Date: 2019-10-15 17:37:56.008437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77cbe143aa4f'
down_revision = 'e2f03f31d93e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reasons',
    sa.Column('reason_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('reason_id')
    )
    op.create_index(op.f('ix_reasons_reason_id'), 'reasons', ['reason_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    op.drop_index(op.f('ix_reasons_reason_id'), table_name='reasons')
    op.drop_table('reasons')
    # ### end Alembic commands ###
