"""init

Revision ID: cf6084d2977e
Revises: cfd68f4585f6
Create Date: 2019-10-13 16:54:25.115303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf6084d2977e'
down_revision = 'cfd68f4585f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labels', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('labels', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('labels', 'updated_at')
    op.drop_column('labels', 'created_at')
    # ### end Alembic commands ###
